create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  name text not null,
  question text not null,
  answer text,
  status text not null default 'pending' check (status in ('pending','answered')),
  votes integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.questions enable row level security;

drop policy if exists "questions_read" on public.questions;
create policy "questions_read"
on public.questions for select
to anon, authenticated
using (true);

drop policy if exists "questions_insert" on public.questions;
create policy "questions_insert"
on public.questions for insert
to anon, authenticated
with check (true);

drop policy if exists "questions_update" on public.questions;
create policy "questions_update"
on public.questions for update
to anon, authenticated
using (true)
with check (true);
